services:
  - type: web
    name: ema-trading-bot
    runtime: docker
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ema-trading-bot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ema-trading-bot-redis
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /

  - type: redis
    name: ema-trading-bot-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: ema-trading-bot-db
    plan: free
    databaseName: ema_trading_bot_production 